# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theinterest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='interest',
        ),
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.ManyToManyField(related_name='theinterest', to='theinterest.Interest'),
        ),
    ]
