# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-25 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='book',
            name='review',
        ),
        migrations.AddField(
            model_name='bookreview',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
