# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='secret',
        ),
        migrations.AddField(
            model_name='secret',
            name='User',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='secretowner', to='secrets.User'),
            preserve_default=False,
        ),
    ]
