# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_in_print'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='in_print',
        ),
    ]
